services:
  render:
    type: web
    name: render
    env: docker
    dockerfilePath: ./docker/Dockerfile.huggingface
    autoDeploy: true
    envVars:
      - key: API_KEY
        value: 0c1ae40adb7d1d7b6758ffe8697c93f1b451c1ecaaa4cb7a81c26450c7e5f824
      - key: SECRET_KEY
        value: 7a120a7ecfbb9d78db8500c964e69320e11a7a8cbd7fab215b8ab0c27bc623b7
      - key: UI_ADMIN_USERNAME
        services:
          - type: web
            name: render
            env: docker
            dockerfilePath: ./docker/Dockerfile.huggingface
            autoDeploy: true
            envVars:
              - key: API_KEY
                value: 0c1ae40adb7d1d7b6758ffe8697c93f1b451c1ecaaa4cb7a81c26450c7e5f824
